### ISSUE TITLE
buggy last version

### ISSUE THREAD

**Issue by isopino** [aminecmi/ReaderforSelfoss#322] opened 2021-01-06 17:22 UTC
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description
Sorry for not beeing more specific in the title but with the latest version from F-Droid I experience several bugs. I hope it's ok to just open one issue for all of them.

1. When using the dark theme the font in the article overview is now black instead of white (black font on dark grey background). So the dark theme is pretty unreadable atm. The article viewer usese the white font as usual.
2. RfS crashes a lot. No better way to descripe it as there is no way to reproduce the crashes. It's just randomly crashing like 10-20 times a day. Never had any such probs with the last version of RfS. 
3. The notification bar icon as well as the notification itself dont disappear anymore. Only way to close them is to force the app to stop via android app details. Works only temporarily though.

### Device

- Samsung Galaxy S7
- Android 8.0
- 1720123583 directly out of F-Droid store

**Comment by aminecmi** [comment] 2021-01-06 17:42
Hello, thanks for the report.

Are you sure that the first issue is related to the update ? I can’t see why this isn’t working anymore.

I’ll look into the remaining issues.

**Comment by isopino** [comment] 2021-01-06 17:45
Pretty sure, as the behaviour with the black font started when I opened the app after I updated some days ago.

**Comment by aminecmi** [comment] 2021-01-06 17:47
Could you please try the previous version and check if the issue is indeed related to the update?

**Comment by isopino** [comment] 2021-01-06 18:05
Works perfectly fine with the previous version...

**Comment by aminecmi** [comment] 2021-01-06 18:12
Thanks for getting back to me. I’ll look into it .

**Comment by isopino** [comment] 2021-01-07 08:11
Tried the update on a Samsung Galaxy Tab 2 running Android 7: same problem regarding the font color. Had not enough time to check for the other two issues though.

**Comment by aminecmi** [comment] 2021-01-07 09:33
You meant the list view, right ? I can't reproduce the issue on the article viewer, but the text in the list view is indead black on grey.

**Comment by davidoskky** [comment] 2021-01-07 18:40
@isopino regarding problem 3: how many unread articles and total articles do you have?
Could you please check how much space is the cache taking? You can find this under the app information in the android settings.

**Comment by isopino** [comment] 2021-01-08 06:49
Cache is approximately 10 MB. Don't know how many articles there are in total...700 - 1000 maybe.

BTW... Clearing the cache didn't help 🤷‍♂️

**Comment by aminecmi** [comment] 2021-01-09 14:07
@isopino I'll close this issue.

The crashes will be fixed by #324. The theme issue is fixed.

**Closed** 2021-01-10 11:13 UTC

**Comment by aminecmi** [comment] 2021-01-10 11:15
@isopino all the issues are now fixed. A new version (1721010101) is ready and waiting fdroid servers to be built.

Thanks for the report.

**Comment by isopino** [comment] 2021-01-10 18:48
Thanks for your support and this great app :)

**Comment by aminecmi** [comment] 2021-01-10 20:21
@isopino no problem at all.

There is a newer version. It's the 1721010102 one, that should fixed everything.
