### ISSUE TITLE
Broken compatibility with selfoss 2.19?

### ISSUE THREAD

**Issue by GutHib** [aminecmi/ReaderforSelfoss#337] opened 2021-03-16 22:17 UTC
Hi,

I updated my server to run php 8, which broke selfoss 2.18. After updating to the latest selfoss 2.19 (nightly, no stable release yet), selfoss is working again, but the reader says it can't retrieve new articles.

Seems that they changed some stuff around in selfoss 2.19 (different folder structure, among other things). Is this on your radar in any way, or should the reader work with selfoss 2.19 just as well as it did with 2.18 (meaning I might have screwed something up)?

Thanks!

**Comment by davidoskky** [comment] 2021-03-17 06:49
Hello!
I am running it with selfoss 2.19, though not the latest release and with php 7.
As far as I know the only breaking api change was in the sources and therefore you cannot add new sources from the app, but everything else should be working.
I will try upgrading to the latest version of selfoss and see what happens, though my server is running an old distribution and I cannot upgrade to php 8 to check if that's causing problems...

**Comment by aminecmi** [comment] 2021-03-17 07:04
Hi @GutHib 

Please follow the issue template with all the needed details.

Also, check your selfoss instance logs to see if it's an issue with selfoss or the app.

Thanks.

**Comment by GutHib** [comment] 2021-03-17 14:35
@davidoskky: What versions of 2.19 and ReaderforSelfoss are you using?

ReaderforSelfoss: 1721010103
Selfoss: 2.19-9af53e9

Upgraded from Selfoss 2.18 to 2.19, following the Selfoss upgrade instructions.
Following the update, ReaderforSelfoss on a rooted Samsung S5 running Android LineageOS reports it can't retrieve new articles. ReaderforSelfoss shows sources, however (so it's clearly logged in). Clicking on "Favorites" will make number of unread articles appear on "New" icon.

Cleaned Cache, Logged out and into ReaderforSelfoss, reinstalled: No change.
Downgrading to Selfoss 2.18 will allow ReaderforSelfoss to retrieve articles again.

Debug log says:

[2021-03-17 14:00:10] selfoss.DEBUG: set cookie on www.mydomain.com/selfoss/ expiring in 2592000 seconds  
[2021-03-17 14:00:13] selfoss.DEBUG: session does not contain valid auth  
[2021-03-17 14:00:13] selfoss.DEBUG: logged in with supplied username and password  
[2021-03-17 14:00:13] selfoss.DEBUG: Established database connection  

Using php 7.4 instead of 8.0 makes no difference.

**Comment by aminecmi** [comment] 2021-03-17 16:52
Thanks for the details.

I'll look into this.

**Comment by davidoskky** [comment] 2021-03-17 17:25
I believe this change in the date format may be the cause of the problem: https://github.com/fossar/selfoss/issues/1246
@GutHib you may try installing the release before that commit, which you can find here: https://bintray.com/fossar/selfoss/selfoss-git/2.19-515cc5b#files

I have been running version c87e14aaba42abe281ca3c859a0006fb292ff22c until now and it works fine.
Unfortunately I cannot test if that particular commit is the cause of the problem as some other problem doesn't allow me to see any article in selfoss itself...

**Comment by GutHib** [comment] 2021-03-17 17:50
@davidoskky: Yup, that fixed it just fine - thank you very much.

Note however that the problem went away by copying the /src/daos folder from the older commit to my current installation - so it might be a different problem after all. If there's any interest, I can track this down further.

**Comment by aminecmi** [comment] 2021-03-22 18:01
This should be fixed. 

I’ll tag the version and it’ll be available on fdroid soon.

**Closed by aminecmi** 2021-03-22 18:01 UTC
