### ISSUE TITLE
Refreshing crashes the app

### ISSUE THREAD

**Issue by cpu2910** [aminecmi/ReaderforSelfoss#229] opened 2018-10-17 09:00 UTC
Hi,
I just ugraded to newest version 1618102863 (F-Droid).
Strange behaviour by opening articles is cleared in #228 

But refreshing the articles by swiping from the top constantly crashes the app.
Clearing cache, Reinstalling the app doesn't solve the problem.

In the settings only the header 'Actions' is shown, but no options underneath...

Nexus 5X, LineageOS 15.1-20181015 (Oreo 8.1.0) 

regards
Christian

**Comment by cpu2910** [comment] 2018-10-17 09:03
Upgrade: The crash while swiping from the top disappeared after switching to card view.
Only problem in settings, common stays.

**Comment by aminecmi** [comment] 2018-10-17 17:37
The issue is fixed and should be available at the same time as #1.

As I'm still testing it, it won't be available just yet. 

If you want, you could download the apk from https://jenkins.amine-bou.fr/job/ReaderForSelfoss/lastSuccessfulBuild/artifact/SignApksBuilder-out/selfoss-key/selfoss/app-githubConfig-release-unsigned.apk/app-githubConfig-release.apk .
It's the alpha version (I'm using it daily without any crash or recurring issue) that contains #1 and fixes your issue.

**Comment by aminecmi** [comment] 2018-10-17 17:40
I'll close this for now.

If you use the alpha APK, you're welcome to provide any useful feedback on #1.

**Closed by aminecmi** 2018-10-17 17:40 UTC
Labels: Status - Fixed somewhere else
