### ISSUE TITLE
Issues with latest updates and Darkmode

### ISSUE THREAD

**Issue by sonicnkt** [aminecmi/ReaderforSelfoss#391] opened 2022-01-05 11:35 UTC
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
* [X] Did you read the `CONTRIBUTING` guide ?

### Description

Im experiening several issues with the latest app updates and the Darkmode.

With the newest build (1721102991-github) pop ups are not displayed in darkmode and the text is unreadable (See Screenshot). This looks fine in 1721102811-github tho. 

I also noticed that after switching i can no longer access the settings menu and the app crashes when trying to do this. If i do not enable dark mode this wont happen. 

### Steps to Reproduce

1. Enable Darkmode in Settings
2. Close App and Restart
3. Try to access settings again

**Expected behavior:** Settings should open

**Actual behavior:** App Crashes

### Screenshots (optional)
![grafik](https://user-images.githubusercontent.com/5454622/148211329-2ffd8902-e77a-40e8-8424-3acaac09dc33.png)

### Device

- OS (Android 9)
- App version (1721102991-github, 1721102811-github)

**Comment by davidoskky** [comment] 2022-01-05 12:42
I do see the first issue, however I cannot reproduce the crash when opening the settings.
I'll be looking into this to find a solution.

**Comment by sonicnkt** [comment] 2022-01-05 12:45
weird, i allready tried deleting all storage/cache and reinstalling but the crash still happens. 
i will try another device to make sure its not my phone.

**Comment by davidoskky** [comment] 2022-01-07 17:16
I was able to reproduce the crash with the latest f-droid version.
This appears to already be solved in the latest github version, thus the next release should fix it.

**Comment by aminecmi** [comment] 2022-01-07 19:40
I'll create a new version now. F-droid server will update the version in a few days tops.

**Comment by aminecmi** [comment] 2022-01-07 19:45
I'll close this. @sonicnkt don't hesitate to open a new issue if you see the problem even after the update.

**Closed** 2022-01-07 19:45 UTC
