### ISSUE TITLE
Chrome Webview is messing up test displaying.

### ISSUE THREAD

**Issue by candardo** [aminecmi/ReaderforSelfoss#285] opened 2019-04-04 07:47 UTC
I've been using the App for quite some time and the article viewer was just fine. Not I always get a black background (its colour was gray with the dark theme) but most important text gest messed up on longer articles. When scrolling text get more messed and parts that were readable (the first part of a post) become messed up too (see screenshot).

I'm running the beta version 1719010271-store on a Nokia 6.1 (TA-1043) and android Pie (march patch).
![Screenshot_20190404-094401_1](https://user-images.githubusercontent.com/6369278/55538319-76e4ec80-56be-11e9-81c2-d44dd9efefee.png)

**Comment by aminecmi** [comment] 2019-04-04 08:17
Thanks for the report.

It was already reported in #282 but I'll keep this one as reference.

**Comment by candardo** [comment] 2019-04-05 20:32
Some more infos:

- sometimes I get black background and sometimes gray (ok with a dark theme) even from the same feed. No clues about this behaviour!
- text gets garbled only if I scroll (fast). when reading an article scrolling it slowly text is fine
- scrolling up fast I get garbled text even on paragraphs the were fine before

**Comment by aminecmi** [comment] 2019-04-06 10:52
@candardo the dark background is fixed !

Still trying to reproduce the text issue.

**Comment by aminecmi** [comment] 2019-04-06 12:10
@candardo reproduced the bug, but I can't find a solution for now.

I pushed an update to the fdroid store, it should be available soon.

**Comment by aminecmi** [comment] 2019-04-06 12:11
I found some kind of workaround where you select the text to see it not grabled. Still searching.

**Comment by shaneonabike** [comment] 2019-04-19 19:31
It's fairly tragic I am also experiencing this. This only just started happening in the last couple of months. If there is anyway I can debug this for you I am more than happy. It makes this pretty difficult to use. For what it's worth it's happening on FullTextRss (setting) and here is an example RSS https://rss.cbc.ca/lineup/topstories.xml

**Comment by aminecmi** [comment] 2019-05-12 19:47
@candardo @shaneonabike sorry for the long wait. 

Is the issue still present ?

I'm not able to reproduce it since a couple of weeks.

If you still see it, could you provide me with the item, the source, the spout, and the icon size set in the settings page ?

Thanks for the help.

**Comment by shaneonabike** [comment] 2019-05-13 17:29
https://rss.cbc.ca/lineup/topstories.xml creates the black issue. The text is just fine but I can't read anything unfortunately.

**Comment by aminecmi** [comment] 2019-05-13 17:36
@shaneonabike the black issue is fixed and should be available in the next f-droid update.

**Comment by shaneonabike** [comment] 2019-05-13 17:39
When will you update the f-droid release?

**Comment by aminecmi** [comment] 2019-05-13 17:44
I can't control anything on fdroid side. The code is available, and the fdroid services will update the app the next time it's built. This could take up to a week.

**Comment by aminecmi** [comment] 2019-05-16 16:55
@shaneonabike just had the update.

**Comment by shaneonabike** [comment] 2019-05-17 14:32
Yeah unfortunately now seems to be crashing everytime I launch the app :/

**Comment by aminecmi** [comment] 2019-05-17 14:35
@shaneonabike yep #286 is tracking this issue. I'll provide an apk as soon as I fix it so you'll be able to use the app until fdroid update is available;.

**Comment by shaneonabike** [comment] 2019-05-23 12:17
I can confirm that this has been resolved and you can close the ticket! Thanks for your awesome app and work!

**Comment by aminecmi** [comment] 2019-05-23 12:21
@shaneonabike did you receive the fdroid update or did you download the apk ?

**Comment by shaneonabike** [comment] 2019-05-23 12:24
I always test with the fdroid so in the latest there all is well

**Comment by aminecmi** [comment] 2019-06-09 13:43
@candardo did the original issue get resolved ?

**Comment by candardo** [comment] 2019-06-09 16:17
Sorry for not replying before. I removed fdroid shortly after trying the
app when the issue was opened. I don't plan to use fdroid right now and I'm
using selfoss right from the browser.

Il dom 9 giu 2019, 15:43 Amine Bou <notifications@github.com> ha scritto:

**Comment by aminecmi** [comment] 2019-06-09 16:25
Ok, I'll close the issue then.

**Comment by jonnyair** [comment] 2019-07-01 17:05
Hi,
I hope it's okay that i comment on an already closed issue, but i have similar problems, see attached images
![Screenshot_20190701-185306](https://user-images.githubusercontent.com/803229/60453926-cfcb0f00-9c32-11e9-9f91-c5c643517c1f.jpg)
![Screenshot_20190701-185222](https://user-images.githubusercontent.com/803229/60453927-cfcb0f00-9c32-11e9-950e-9483a386d043.jpg)
in both cases text overlays other elements (text or an image) which should not happen - and it looks fine on the web.
i had the same issue with images overlaying other images, too but that's rare and i don't have an example at hand right now.

anyhow - i hope it's okay to highjack this issue, if not, let me know and i'll open a new one :-)

**Comment by aminecmi** [comment] 2019-07-01 20:32
Hi, thanks for the report.

I was able to reproduce the issue one time only, and never really had a chance to fix it.

Could you give me more details about your phone, your Android version, the app version and "Android system Webview" app version please?

**Comment by jonnyair** [comment] 2019-07-01 20:36
sure thing!
Phone: OnePlus 5t 
OS: OxygenOS 9.0.6 (Android 9  with May 2019 Patchlevel)
WebView: Chrome 75.0.3770.101 (selected)
Android System Webview: 68.0.340.91 (disabled)

**Comment by aminecmi** [comment] 2019-07-01 20:41
Could you try to update your Android system Webview app ?

I have a different version, it may be related to this

![Screenshot_20190701-222905](https://user-images.githubusercontent.com/510304/60465425-57c01180-9c51-11e9-971d-6641b1a31cab.jpg)

**Comment by jonnyair** [comment] 2019-07-01 21:42
i just installed the latest stable version from apkmirror but the version didn't change - and it's still disabled in the settings (and in play store). chrome is selected.
i googled a bit and found this article https://www.androidpolice.com/2016/07/20/google-explains-chrome-will-become-webview-android-7-0/ 

or do you have an idea how to enable/activate system webview?

**Comment by aminecmi** [comment] 2019-07-02 04:13
Not really sorry.

I'm not using chrome on my phone and it's disabled. Maybe it's the reason I only have the system Webview ?

If it's not too much of a hassle could you try disabling chrome and testing again?

**Comment by jonnyair** [comment] 2019-07-02 09:00
yeah, that's what i checked when i wrote that the system webview ist disabled, see attached screenshot:
![Screenshot_20190702-105824__01](https://user-images.githubusercontent.com/803229/60499314-7dcccc80-9cb8-11e9-9430-76e2b3de1a2f.jpg)
it's disabled and can't be selected, it's also disabled in playstore and in the app-list (settings -> apps), i can't enable it anywhere.

**Comment by aminecmi** [comment] 2019-07-02 09:02
Maybe you could try disabling chrome ? 

I have it disabled and the default System app is enabled in my settings.

**Comment by aminecmi** [comment] 2019-07-06 12:33
@jonnyair any news on this ?

**Comment by jonnyair** [comment] 2019-07-08 16:17
Hi, 
Sorry i was a bit busy the last few days, but i had a few minutes at hand right now so i disabled Chrome and afterwards  ReaderforSelfoss wasn't able to start, i went into the Play Store and was able to upgrade the WebView app to the latest version (78), after that everything seemed to be working! 
Now i need chrome - so i enabled it again but Google in all his wisdom desided to revert the Android system WebView to 68.0.3440.91. Which is the same Version as before and gave me the same Render-Issues...

Conclusion: yes it depends on the rendering engine but why does ReaderforSelfos not use Chrome? AFAIK (i haven't done any android dev, but that's my understanding) the default WebView should be used by apps unless they specifically ask for a different one.
sure it would be best if i could upgrade the system webview but google won't let me...

**Comment by aminecmi** [comment] 2019-07-08 16:25
From my understanding, the chrome version is an old/bugged version, so the in-app reader will be bugged. You may want to disable the in app reader to solve your issue. I can't do anything about this as the Webview renderer choosen by the system.

**Comment by jonnyair** [comment] 2019-07-08 17:33
actually - it's the other way around: the system WebView is old, Chrome is new (since Android 7):
https://developer.android.com/about/versions/nougat/android-7.0#chrome-+-webview,-together

**Comment by aminecmi** [comment] 2019-07-08 17:39
The version is set to an old one when chrome is installed. When it's not, it's the same as the chrome one, still, the system one works as intended.

Chrome app is messing with things. 

Could you try to use a newer version of chrome (dev/canary) and change the rendering thing in the settings to see if the issue is solved ?

**Comment by jonnyair** [comment] 2019-07-08 20:14
nice idea - but didn't work unfortunately.
I think, that ReaderforSelfoss still uses the old WebView and NOT the selected one (Chrome, Chrome Beta or Chrome Dev), if that makes sense?

**Comment by aminecmi** [comment] 2019-07-09 11:09
The app uses a Webview ([here](https://github.com/aminecmi/ReaderforSelfoss/blob/master/app/src/main/res/layout/fragment_article.xml#L58)) to display the article content as it's html.

The app itself DO NOT specify anything to choose a webview renderer and according to [this](https://developer.android.com/about/versions/nougat/android-7.0.html#webview) Chrome is used by default (if enabled) since Android 7.0.

**Comment by aminecmi** [comment] 2020-01-27 21:04
Chrome isn't the default webview anymore.

I'll close this since it should be fixed with the new webview system.

**Closed by aminecmi** 2020-01-27 21:04 UTC
Labels: Status = Need more details
